### ISSUE TITLE
synetfind <Signals.SIGABRT: 6>

### ISSUE THREAD

**Issue by hcli007** [hcli007/SNN_pipeline#2]
During the batch hmmsearch process using the **synetfind module**, sporadic errors may occur, mainly indicated as **<Signals.SIGABRT: 6>**. The cause is the limitation of hmmsearch in handling target sequences with **100,000 amino acid** residues. It is recommended to use the `seqkit` tool and examine the protein file through the command `seqkit fx2tab --length --name --header-line your_file.fasta > lengths.txt`.

**Comment by shuan-star** [comment]
When i used the synetfind -i module using test file wrapped in github, i got the following error, i am not family with python3 language. but i guess there may some mistakes when preparing files.
Execution parameters:   /home/songhuan/anaconda3/envs/snn_pipline/bin/synetbuild -i /mnt/g/SNN_pipeline-main/species_list -d /mnt/g/SNN_pipeline-main/test-data --out_dir /mnt/g/SNN_pipeline-main/out
Traceback (most recent call last):
  File "/home/songhuan/anaconda3/envs/snn_pipline/bin/synetbuild", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/home/songhuan/anaconda3/envs/snn_pipline/lib/python3.13/site-packages/snn_pipeline/synetbuild.py", line 205, in main
    synet_build(complete_path(args.species_namelist_file), complete_path(args.data_path), complete_path(args.out_dir),
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                args.hits, args.anchors, args.gaps, args.threads, duplicate, tandem)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/songhuan/anaconda3/envs/snn_pipline/lib/python3.13/site-packages/snn_pipeline/synetbuild.py", line 56, in synet_build
    running = subprocess.check_output(["jobs", "-p"], universal_newlines=True)
  File "/home/songhuan/anaconda3/envs/snn_pipline/lib/python3.13/subprocess.py", line 472, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
               **kwargs).stdout
               ^^^^^^^^^
  File "/home/songhuan/anaconda3/envs/snn_pipline/lib/python3.13/subprocess.py", line 554, in run
    with Popen(*popenargs, **kwargs) as process:
         ~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/home/songhuan/anaconda3/envs/snn_pipline/lib/python3.13/subprocess.py", line 1036, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        pass_fds, cwd, env,
                        ^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
                        gid, gids, uid, umask,
                        ^^^^^^^^^^^^^^^^^^^^^^
                        start_new_session, process_group)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/songhuan/anaconda3/envs/snn_pipline/lib/python3.13/subprocess.py", line 1966, in _execute_child

**Comment by hcli007** [comment]
> When i used the synetfind -i module using test file wrapped in github, i got the following error, i am not family with python3 language. but i guess there may some mistakes when preparing files. Execution parameters: /home/songhuan/anaconda3/envs/snn_pipline/bin/synetbuild -i /mnt/g/SNN_pipeline-main/species_list -d /mnt/g/SNN_pipeline-main/test-data --out_dir /mnt/g/SNN_pipeline-main/out Traceback (most recent call last): File "/home/songhuan/anaconda3/envs/snn_pipline/bin/synetbuild", line 8, in sys.exit(main()) ~~~~^^ File "/home/songhuan/anaconda3/envs/snn_pipline/lib/python3.13/site-packages/snn_pipeline/synetbuild.py", line 205, in main synet_build(complete_path(args.species_namelist_file), complete_path(args.data_path), complete_path(args.out_dir), ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ args.hits, args.anchors, args.gaps, args.threads, duplicate, tandem) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/songhuan/anaconda3/envs/snn_pipline/lib/python3.13/site-packages/snn_pipeline/synetbuild.py", line 56, in synet_build running = subprocess.check_output(["jobs", "-p"], universal_newlines=True) File "/home/songhuan/anaconda3/envs/snn_pipline/lib/python3.13/subprocess.py", line 472, in check_output return run(*popenargs, stdout=PIPE, timeout=timeout, check=True, ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ **kwargs).stdout ^^^^^^^^^ File "/home/songhuan/anaconda3/envs/snn_pipline/lib/python3.13/subprocess.py", line 554, in run with Popen(*popenargs, **kwargs) as process: ~~~~~^^^^^^^^^^^^^^^^^^^^^^ File "/home/songhuan/anaconda3/envs/snn_pipline/lib/python3.13/subprocess.py", line 1036, in **init** self._execute_child(args, executable, preexec_fn, close_fds, ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ pass_fds, cwd, env, ^^^^^^^^^^^^^^^^^^^ ...<5 lines>... gid, gids, uid, umask, ^^^^^^^^^^^^^^^^^^^^^^ start_new_session, process_group) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/songhuan/anaconda3/envs/snn_pipline/lib/python3.13/subprocess.py", line 1966, in _execute_child

This issue is caused by some Linux versions not having built-in `jobs` command, which has been fixed in the **0.2.5 version** update of `snn_pipeline`.
